### ISSUE TITLE
As a user I can try the app before registering

### ISSUE THREAD

**Issue by GiuliaTeggi** [fac-13/allauda#4]
As a user I can:
- [x] Click the button on the landing page to try the app without registering #5 
- [ ] Read more about what the app does #6 
- [x]  Click on a gift icon #7 
- [x]  Scroll down to look at some pictures  #11 
- [x] Click on a button to go back to the landing page #12
