### ISSUE TITLE
As a user I can register and set up preferences in order to use the app 

### ISSUE THREAD

**Issue by isnotafunction** [fac-13/allauda#8]
As a user I can:
- [x] access signup form.[#43](https://github.com/fac-13/allauda/issues/43)
- [x] set my username and password. #45 #44 
- [ ] set my age range, time zone and wake up time. #46 
- [ ] click on boxes to set my preferences regarding content. #46 
- [ ] click on a submit button to complete my registration. #47 
- [x] receive a confirmation that my registration is successful.  #47

**Comment by Parissai** [comment]
@isnotafunction @GiuliaTeggi @missKatiaPunter We could close this.
